# Generated by Django 4.0.6 on 2022-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_delete_aboutfilms'),
        ('place', '0002_place_delete_aboutconcerts'),
        ('film', '0003_rename_photo_film_img_alter_film_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='place',
            field=models.ManyToManyField(related_name='places', to='place.place', verbose_name='Кинотеатр'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='timetable',
        ),
        migrations.AddField(
            model_name='film',
            name='timetable',
            field=models.ManyToManyField(related_name='timetables', to='timetable.timetable', verbose_name='Расписание сеансов'),
        ),
    ]
