# Generated by Django 4.0.6 on 2022-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_options'),
        ('film', '0004_film_place_remove_film_timetable_film_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='timetable',
            field=models.ManyToManyField(related_name='timetables', to='timetable.timetable', verbose_name='Расписание '),
        ),
    ]
