# Generated by Django 4.0.6 on 2023-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('film', '0006_film_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='genre.genre', verbose_name='Жанр'),
        ),
    ]
