# Generated by Django 4.0.6 on 2023-01-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='pagination',
            field=models.IntegerField(default=1, verbose_name='Пагинация'),
        ),
    ]
