# Generated by Django 4.0.6 on 2023-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_remove_film_pagination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='createDate',
        ),
        migrations.AddField(
            model_name='film',
            name='createDate',
            field=models.CharField(default=1204, max_length=4, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
