# Generated by Django 4.0.6 on 2023-01-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_film_description_en_film_description_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFilm',
        ),
    ]
