# Generated by Django 4.0.6 on 2023-01-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_historicalfilm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFilm',
        ),
    ]
