# Generated by Django 4.0.6 on 2022-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutfilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='кинотетар')),
                ('timetable', models.TimeField(verbose_name='Сеансы ')),
            ],
            options={
                'verbose_name': 'О кино',
                'verbose_name_plural': 'О кино',
            },
        ),
    ]
