# Generated by Django 4.0.6 on 2022-07-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_delete_aboutfilms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание ', 'verbose_name_plural': 'Расписания '},
        ),
    ]
