# Generated by Django 4.0.6 on 2022-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['time'], 'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='Время'),
        ),
    ]
