# Generated by Django 4.0.6 on 2023-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetable_options_remove_timetable_timetable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
