# Generated by Django 4.0.6 on 2022-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_delete_aboutconcerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Концертный зал/Кинотеатр'),
        ),
    ]
