# Generated by Django 4.0.6 on 2023-01-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Дата создания',
                'verbose_name_plural': 'Дата создания',
            },
        ),
    ]
