# Generated by Django 4.0.6 on 2023-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdate',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
