# Generated by Django 4.0.6 on 2023-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDate', '0002_alter_createdate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createdate',
            options={'verbose_name': 'Дата выхода', 'verbose_name_plural': 'Дата выхода'},
        ),
        migrations.AlterField(
            model_name='createdate',
            name='date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
