# Generated by Django 4.0.6 on 2023-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDate', '0003_alter_createdate_options_alter_createdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdate',
            name='date',
            field=models.TextField(verbose_name='Дата выхода'),
        ),
    ]
