# Generated by Django 4.0.6 on 2023-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDate', '0005_alter_createdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdate',
            name='date',
            field=models.IntegerField(verbose_name='Дата выхода'),
        ),
    ]
