# Generated by Django 4.0.6 on 2022-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_alter_concert_photo_favoriteconcert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='photo',
            new_name='img',
        ),
    ]
