# Generated by Django 4.0.6 on 2022-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_place'),
        ('timetable', '0002_timetable_delete_aboutfilms'),
        ('concert', '0004_alter_concert_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='place',
            field=models.ManyToManyField(related_name='placesForConterts', to='place.place', verbose_name='Концертный зал'),
        ),
        migrations.AddField(
            model_name='concert',
            name='timetable',
            field=models.ManyToManyField(related_name='timetablesForConterts', to='timetable.timetable', verbose_name='Дата проведения'),
        ),
    ]
