# Generated by Django 4.0.6 on 2022-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_options'),
        ('concert', '0005_concert_place_concert_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='timetable',
            field=models.ManyToManyField(related_name='timetablesForConterts', to='timetable.timetable', verbose_name='Расписание '),
        ),
    ]
