# Generated by Django 4.0.6 on 2023-01-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDate', '0001_initial'),
        ('concert', '0006_alter_concert_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='createDate',
            field=models.ManyToManyField(related_name='createDatesForConterts', to='createDate.createdate', verbose_name='Дата создания'),
        ),
    ]
