# Generated by Django 4.0.6 on 2023-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('concert', '0007_concert_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.ManyToManyField(related_name='genresForConterts', to='genre.genre', verbose_name='Жанр'),
        ),
    ]
