# Generated by Django 4.0.6 on 2023-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0008_concert_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='createDate',
        ),
        migrations.AddField(
            model_name='concert',
            name='createDate',
            field=models.CharField(default=1000, max_length=4, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
