# Generated by Django 4.0.6 on 2023-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0009_remove_concert_createdate_concert_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='createDate',
            field=models.IntegerField(max_length=4, verbose_name='Дата создания'),
        ),
    ]
